export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const TOGGLE_TODO_ITEM = 'TOGGLE_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';

export const SWITCH_FILTER = 'SWITCH_FILTER';

export const SAVE_TODOS = 'SAVE_TODOS';
export const LOAD_TODOS = 'LOAD_TODOS';
export const SET_TODO_IS_FETCHING = 'SET_TODO_IS_FETCHING';
export const STORE_TODO_ITEMS = 'STORE_TODO_ITEMS';
